# Generated by Django 3.0.3 on 2020-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('salary', models.PositiveIntegerField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('dress', models.CharField(max_length=200)),
            ],
        ),
    ]
