# Generated by Django 3.0.3 on 2020-07-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200708_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dress',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='season',
        ),
    ]
